"""create phase 1-8 schema

Revision ID: 0cfadf2acb52
Revises:
Create Date: 2026-08-09 19:48:11.852236
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0cfadf2acb52"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_batches",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Internal identifier for this ingestion envelope.",
        ),
        sa.Column(
            "source_system",
            sa.String(length=64),
            nullable=False,
            comment="Namespace of the producer, such as the platform form or a future adapter.",
        ),
        sa.Column(
            "source_format",
            sa.String(length=32),
            nullable=False,
            comment="Controlled input boundary: structured_form, csv, or external_integration.",
        ),
        sa.Column(
            "idempotency_key",
            sa.String(length=255),
            nullable=False,
            comment="Producer key reused on retry so the same batch is not imported twice.",
        ),
        sa.Column(
            "external_batch_id",
            sa.String(length=255),
            nullable=True,
            comment="Optional source-provided batch identifier; not the internal primary key.",
        ),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default="received",
            nullable=False,
            comment="Ingest result: received, completed, or rejected.",
        ),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the platform received this source envelope.",
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When processing completed; NULL while the batch is not completed.",
        ),
        sa.Column(
            "rejection_reason",
            sa.String(length=500),
            nullable=True,
            comment="Reason required when the batch is rejected; not a failure lifecycle model.",
        ),
        sa.CheckConstraint(
            "source_format IN ('structured_form', 'csv', 'external_integration')",
            name="ck_import_batches_source_format",
        ),
        sa.CheckConstraint(
            "status <> 'rejected' OR rejection_reason IS NOT NULL",
            name="ck_import_batches_rejection_reason",
        ),
        sa.CheckConstraint(
            "status IN ('received', 'completed', 'rejected')", name="ck_import_batches_status"
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR completed_at >= received_at",
            name="ck_import_batches_completion_time",
        ),
        sa.CheckConstraint(
            "length(btrim(idempotency_key)) > 0", name="ck_import_batches_idempotency_key_nonempty"
        ),
        sa.CheckConstraint(
            "length(btrim(source_system)) > 0", name="ck_import_batches_source_system_nonempty"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "source_system", name="uq_import_batches_id_source_system"),
        sa.UniqueConstraint(
            "source_system", "idempotency_key", name="uq_import_batches_source_idempotency"
        ),
    )
    op.create_table(
        "organisations",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Internal stable identifier; not a display name or external source identifier.",
        ),
        sa.Column(
            "name",
            sa.String(length=200),
            nullable=False,
            comment="Current display name; renames must not change the internal identity.",
        ),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default="active",
            nullable=False,
            comment="Lifecycle state; inactive organisations remain available to history.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this canonical identity was created.",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the canonical identity fields were last changed.",
        ),
        sa.CheckConstraint("status IN ('active', 'inactive')", name="ck_organisations_status"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Internal actor identity; not an authentication provider subject.",
        ),
        sa.Column(
            "display_name",
            sa.String(length=200),
            nullable=False,
            comment="Operational display name used by authorised workflow actors.",
        ),
        sa.Column(
            "email",
            sa.String(length=320),
            nullable=True,
            comment="Optional login/contact identity; normalise before writing and protect from general API reads.",
        ),
        sa.Column(
            "password_hash",
            sa.String(length=255),
            nullable=True,
            comment="Argon2id/bcrypt-style encoded hash only; never store a plaintext password.",
        ),
        sa.Column(
            "oauth_provider",
            sa.String(length=64),
            nullable=True,
            comment="OAuth/OIDC provider namespace, stored with oauth_subject.",
        ),
        sa.Column(
            "oauth_subject",
            sa.String(length=255),
            nullable=True,
            comment="Opaque provider subject; not a display name or internal actor ID.",
        ),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default="active",
            nullable=False,
            comment="Actor lifecycle; inactive users remain available to history.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this business actor identity was created.",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this business actor identity was last changed.",
        ),
        sa.CheckConstraint("status IN ('active', 'inactive')", name="ck_users_status"),
        sa.CheckConstraint(
            "(oauth_provider IS NULL) = (oauth_subject IS NULL)",
            name="ck_users_oauth_identity_pair",
        ),
        sa.CheckConstraint(
            "password_hash IS NULL OR email IS NOT NULL", name="ck_users_password_requires_email"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("oauth_provider", "oauth_subject", name="uq_users_oauth_identity"),
    )
    op.create_index("uq_users_email_ci", "users", [sa.literal_column("lower(email)")], unique=True)
    op.create_table(
        "organisation_roles",
        sa.Column(
            "id", sa.Uuid(), nullable=False, comment="Internal identifier for this role period."
        ),
        sa.Column(
            "organisation_id",
            sa.Uuid(),
            nullable=False,
            comment="Organisation whose role is represented.",
        ),
        sa.Column(
            "role_type",
            sa.String(length=32),
            nullable=False,
            comment="Controlled role: donor, recipient, hub, or food_rescue_operator.",
        ),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Inclusive start of the role's validity period.",
        ),
        sa.Column(
            "valid_until",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Exclusive end of the role's validity period; NULL means no recorded end.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this role period was recorded.",
        ),
        sa.CheckConstraint(
            "role_type IN ('donor', 'recipient', 'hub', 'food_rescue_operator')",
            name="ck_organisation_roles_role_type",
        ),
        sa.CheckConstraint(
            "valid_until IS NULL OR valid_until > valid_from",
            name="ck_organisation_roles_valid_period",
        ),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organisation_id",
            "role_type",
            "valid_from",
            name="uq_organisation_roles_identity_period",
        ),
    )
    op.create_table(
        "route_planning_runs",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Internal identity for one driver planning session.",
        ),
        sa.Column(
            "driver_user_id",
            sa.Uuid(),
            nullable=False,
            comment="Driver whose bounded planning session is represented.",
        ),
        sa.Column(
            "planning_horizon_start",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Inclusive planning horizon start.",
        ),
        sa.Column(
            "planning_horizon_end",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Exclusive planning horizon end.",
        ),
        sa.Column(
            "planned_departure_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Departure time used when evaluating route feasibility.",
        ),
        sa.Column(
            "policy_version",
            sa.String(length=64),
            nullable=False,
            comment="Approved route priority and feasibility policy version.",
        ),
        sa.Column(
            "model_identifier",
            sa.String(length=128),
            nullable=True,
            comment="Optional agent/model identifier; proposal is not a commitment.",
        ),
        sa.Column(
            "status",
            sa.String(length=24),
            server_default="started",
            nullable=False,
            comment="Planning state before a human commits a delivery.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the planning run was created.",
        ),
        sa.CheckConstraint(
            "status IN ('started', 'proposal_ready', 'approved', 'committed')",
            name="ck_route_planning_runs_status",
        ),
        sa.CheckConstraint(
            "planning_horizon_end > planning_horizon_start", name="ck_route_planning_runs_horizon"
        ),
        sa.ForeignKeyConstraint(["driver_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sites",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Internal stable identifier for this operational site.",
        ),
        sa.Column(
            "organisation_id",
            sa.Uuid(),
            nullable=False,
            comment="Organisation that owns or operates this site.",
        ),
        sa.Column(
            "name",
            sa.String(length=200),
            nullable=False,
            comment="Current site display name; not used as the internal identity.",
        ),
        sa.Column(
            "site_type",
            sa.String(length=32),
            nullable=False,
            comment="Controlled site kind: store, branch, warehouse, or service_site.",
        ),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default="active",
            nullable=False,
            comment="Lifecycle state; inactive sites remain available to history.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this site identity was created.",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the site identity fields were last changed.",
        ),
        sa.CheckConstraint(
            "site_type IN ('store', 'branch', 'warehouse', 'service_site')",
            name="ck_sites_site_type",
        ),
        sa.CheckConstraint("status IN ('active', 'inactive')", name="ck_sites_status"),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "organisation_id", name="uq_sites_id_organisation"),
    )
    op.create_table(
        "source_records",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Internal source-record identity; never the external record key.",
        ),
        sa.Column(
            "import_batch_id",
            sa.Uuid(),
            nullable=False,
            comment="Ingestion envelope that supplied this record.",
        ),
        sa.Column(
            "source_system",
            sa.String(length=64),
            nullable=False,
            comment="Source namespace; must match the linked import batch.",
        ),
        sa.Column(
            "source_record_type",
            sa.String(length=64),
            nullable=False,
            comment="Producer-defined record kind, such as donation_listing or product.",
        ),
        sa.Column(
            "external_record_id",
            sa.String(length=255),
            nullable=False,
            comment="Stable source identity used for idempotent re-imports.",
        ),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the source observed the record; NULL means the source did not provide it.",
        ),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When FoodFlow recorded this source record.",
        ),
        sa.Column(
            "raw_reference",
            sa.String(length=500),
            nullable=False,
            comment="Pointer to the source row/submission/object used for provenance.",
        ),
        sa.Column(
            "raw_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Optional source snapshot; must not contain secrets or unbounded unrelated data.",
        ),
        sa.Column(
            "ingest_status",
            sa.String(length=16),
            server_default="received",
            nullable=False,
            comment="Record ingest result: received, accepted, or rejected.",
        ),
        sa.Column(
            "ingest_message",
            sa.String(length=500),
            nullable=True,
            comment="Validation result or rejection message when supplied.",
        ),
        sa.CheckConstraint(
            "ingest_status <> 'rejected' OR ingest_message IS NOT NULL",
            name="ck_source_records_rejection_message",
        ),
        sa.CheckConstraint(
            "ingest_status IN ('received', 'accepted', 'rejected')",
            name="ck_source_records_ingest_status",
        ),
        sa.CheckConstraint(
            "length(btrim(external_record_id)) > 0", name="ck_source_records_external_id_nonempty"
        ),
        sa.CheckConstraint(
            "length(btrim(source_record_type)) > 0", name="ck_source_records_type_nonempty"
        ),
        sa.CheckConstraint(
            "length(btrim(source_system)) > 0", name="ck_source_records_source_system_nonempty"
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id", "source_system"],
            ["import_batches.id", "import_batches.source_system"],
            name="fk_source_records_batch_source_system",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_system",
            "source_record_type",
            "external_record_id",
            name="uq_source_records_external_identity",
        ),
    )
    op.create_table(
        "donations",
        sa.Column(
            "id", sa.Uuid(), nullable=False, comment="Internal identity for one donor supply event."
        ),
        sa.Column(
            "source_site_id",
            sa.Uuid(),
            nullable=False,
            comment="Verified donor site where this supply event can be collected.",
        ),
        sa.Column(
            "created_by_user_id",
            sa.Uuid(),
            nullable=False,
            comment="Business actor who created the donation listing.",
        ),
        sa.Column(
            "source_record_id",
            sa.Uuid(),
            nullable=True,
            comment="Optional external source provenance; not the donation identity.",
        ),
        sa.Column(
            "pickup_window_start",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Inclusive earliest collection time.",
        ),
        sa.Column(
            "pickup_window_end",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Exclusive latest collection time.",
        ),
        sa.Column(
            "safe_deadline",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Latest safe delivery target used by future feasibility checks.",
        ),
        sa.Column(
            "status",
            sa.String(length=24),
            server_default="draft",
            nullable=False,
            comment="Current success-path state; detailed history is append-only events.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the donation aggregate was created.",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When current donation fields were last changed.",
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'listed', 'manual_review', 'hard_blocked', 'collected', 'delivered')",
            name="ck_donations_status",
        ),
        sa.CheckConstraint(
            "pickup_window_end > pickup_window_start", name="ck_donations_pickup_window"
        ),
        sa.CheckConstraint(
            "safe_deadline > pickup_window_start", name="ck_donations_safe_deadline"
        ),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_record_id"], ["source_records.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_site_id"], ["sites.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "food_products",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Internal reusable product identity; GTIN is not the primary key.",
        ),
        sa.Column(
            "gtin",
            sa.String(length=14),
            nullable=False,
            comment="Canonical digits-only GTIN-8/12/13/14; barcode mapping remains optional per item.",
        ),
        sa.Column(
            "product_name",
            sa.String(length=200),
            nullable=False,
            comment="Current reusable product name; future item snapshots copy facts separately.",
        ),
        sa.Column(
            "brand",
            sa.String(length=200),
            nullable=True,
            comment="Optional reusable brand identity.",
        ),
        sa.Column(
            "variant",
            sa.String(length=200),
            nullable=True,
            comment="Optional size/flavour/variant description.",
        ),
        sa.Column(
            "source_record_id",
            sa.Uuid(),
            nullable=True,
            comment="Optional provenance record used to establish this product identity.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this reusable product identity was created.",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the current reusable product fields were last changed.",
        ),
        sa.CheckConstraint(
            "gtin ~ '^[0-9]{8}$' OR gtin ~ '^[0-9]{12}$' OR gtin ~ '^[0-9]{13}$' OR gtin ~ '^[0-9]{14}$'",
            name="ck_food_products_gtin_format",
        ),
        sa.ForeignKeyConstraint(["source_record_id"], ["source_records.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gtin", name="uq_food_products_gtin"),
    )
    op.create_table(
        "organisation_memberships",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Internal identifier for this membership period.",
        ),
        sa.Column(
            "user_id", sa.Uuid(), nullable=False, comment="Business actor holding this membership."
        ),
        sa.Column(
            "organisation_id",
            sa.Uuid(),
            nullable=False,
            comment="Organisation in which the role is valid.",
        ),
        sa.Column(
            "site_id",
            sa.Uuid(),
            nullable=True,
            comment="Target site when scope_type is site; NULL means organisation scope.",
        ),
        sa.Column(
            "scope_type",
            sa.String(length=16),
            server_default="organisation",
            nullable=False,
            comment="Explicit authority scope: organisation or site.",
        ),
        sa.Column(
            "membership_role",
            sa.String(length=32),
            nullable=False,
            comment="Controlled role: driver, coordinator, or recipient_responder.",
        ),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Inclusive start of the membership validity period.",
        ),
        sa.Column(
            "valid_until",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Exclusive end; a new membership period preserves history.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this membership period was recorded.",
        ),
        sa.CheckConstraint(
            "(scope_type = 'organisation' AND site_id IS NULL) OR (scope_type = 'site' AND site_id IS NOT NULL)",
            name="ck_organisation_memberships_scope_target",
        ),
        sa.CheckConstraint(
            "membership_role <> 'recipient_responder' OR scope_type = 'site'",
            name="ck_organisation_memberships_recipient_site_scope",
        ),
        sa.CheckConstraint(
            "membership_role IN ('driver', 'coordinator', 'recipient_responder')",
            name="ck_organisation_memberships_role",
        ),
        sa.CheckConstraint(
            "scope_type IN ('organisation', 'site')", name="ck_organisation_memberships_scope_type"
        ),
        sa.CheckConstraint(
            "valid_until IS NULL OR valid_until > valid_from",
            name="ck_organisation_memberships_valid_period",
        ),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["site_id", "organisation_id"],
            ["sites.id", "sites.organisation_id"],
            name="fk_organisation_memberships_site_organisation",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "organisation_id",
            "site_id",
            "membership_role",
            "valid_from",
            name="uq_organisation_memberships_identity_period",
        ),
    )
    op.create_table(
        "recipient_availability_snapshots",
        sa.Column(
            "id", sa.Uuid(), nullable=False, comment="Internal identity for one capacity snapshot."
        ),
        sa.Column(
            "site_id",
            sa.Uuid(),
            nullable=False,
            comment="Recipient site whose current capacity is represented.",
        ),
        sa.Column(
            "food_category",
            sa.String(length=64),
            nullable=False,
            comment="Food category or matching lane for this capacity.",
        ),
        sa.Column(
            "storage_class",
            sa.String(length=16),
            nullable=False,
            comment="Storage lane for this capacity snapshot.",
        ),
        sa.Column(
            "capacity_status",
            sa.String(length=8),
            nullable=False,
            comment="Known zero is different from unknown capacity.",
        ),
        sa.Column(
            "available_quantity",
            sa.Numeric(precision=12, scale=3),
            nullable=True,
            comment="Remaining capacity when capacity_status is known.",
        ),
        sa.Column(
            "quantity_unit",
            sa.String(length=16),
            nullable=False,
            comment="Unit of available_quantity.",
        ),
        sa.Column(
            "receiving_window_start",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Inclusive receiving-window start.",
        ),
        sa.Column(
            "receiving_window_end",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Exclusive receiving-window end.",
        ),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When the operator/provider observed the capacity.",
        ),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When FoodFlow recorded the snapshot.",
        ),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Inclusive start of the snapshot validity window.",
        ),
        sa.Column(
            "valid_until",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Exclusive freshness boundary; stale data is not current capacity.",
        ),
        sa.Column(
            "visibility",
            sa.String(length=16),
            server_default="operational",
            nullable=False,
            comment="Operational or protected capacity visibility.",
        ),
        sa.Column(
            "updated_by_user_id",
            sa.Uuid(),
            nullable=False,
            comment="Operator responsible for this snapshot.",
        ),
        sa.Column(
            "source_record_id",
            sa.Uuid(),
            nullable=True,
            comment="Optional external provenance for a capacity observation.",
        ),
        sa.CheckConstraint(
            "(capacity_status = 'known' AND available_quantity IS NOT NULL AND available_quantity >= 0) OR (capacity_status = 'unknown' AND available_quantity IS NULL)",
            name="ck_recipient_availability_quantity_semantics",
        ),
        sa.CheckConstraint(
            "capacity_status IN ('known', 'unknown')",
            name="ck_recipient_availability_capacity_status",
        ),
        sa.CheckConstraint(
            "quantity_unit IN ('kg', 'g', 'unit', 'case', 'box', 'crate', 'litre', 'ml')",
            name="ck_recipient_availability_quantity_unit",
        ),
        sa.CheckConstraint(
            "storage_class IN ('ambient', 'chilled', 'frozen', 'any')",
            name="ck_recipient_availability_storage_class",
        ),
        sa.CheckConstraint(
            "visibility IN ('operational', 'protected')",
            name="ck_recipient_availability_visibility",
        ),
        sa.CheckConstraint(
            "receiving_window_end > receiving_window_start",
            name="ck_recipient_availability_receiving_window",
        ),
        sa.CheckConstraint(
            "valid_until > valid_from", name="ck_recipient_availability_valid_period"
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_record_id"], ["source_records.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recipient_capabilities",
        sa.Column(
            "id", sa.Uuid(), nullable=False, comment="Internal identity for one capability version."
        ),
        sa.Column(
            "site_id",
            sa.Uuid(),
            nullable=False,
            comment="Recipient operational site to which the capability applies.",
        ),
        sa.Column(
            "food_category",
            sa.String(length=64),
            nullable=False,
            comment="Food category or matching lane; taxonomy is intentionally data-driven.",
        ),
        sa.Column(
            "storage_class",
            sa.String(length=16),
            nullable=False,
            comment="Storage lane accepted by the site.",
        ),
        sa.Column(
            "visibility",
            sa.String(length=16),
            server_default="operational",
            nullable=False,
            comment="Operational or protected recipient-state visibility.",
        ),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Inclusive start of this capability version.",
        ),
        sa.Column(
            "valid_until",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Exclusive end; NULL means no recorded end.",
        ),
        sa.Column(
            "updated_by_user_id",
            sa.Uuid(),
            nullable=False,
            comment="Operator responsible for this capability version.",
        ),
        sa.Column(
            "notes",
            sa.String(length=500),
            nullable=True,
            comment="Operational handling note; not a substitute for the controlled lane.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this capability version was recorded.",
        ),
        sa.CheckConstraint(
            "storage_class IN ('ambient', 'chilled', 'frozen', 'any')",
            name="ck_recipient_capabilities_storage_class",
        ),
        sa.CheckConstraint(
            "visibility IN ('operational', 'protected')",
            name="ck_recipient_capabilities_visibility",
        ),
        sa.CheckConstraint(
            "valid_until IS NULL OR valid_until > valid_from",
            name="ck_recipient_capabilities_valid_period",
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "site_id",
            "food_category",
            "storage_class",
            "valid_from",
            name="uq_recipient_capabilities_version",
        ),
    )
    op.create_table(
        "recipient_needs",
        sa.Column(
            "id", sa.Uuid(), nullable=False, comment="Internal identity for one need declaration."
        ),
        sa.Column(
            "site_id", sa.Uuid(), nullable=False, comment="Recipient site declaring the need."
        ),
        sa.Column(
            "food_category",
            sa.String(length=64),
            nullable=False,
            comment="Food category or matching lane requested by the site.",
        ),
        sa.Column(
            "storage_class",
            sa.String(length=16),
            nullable=False,
            comment="Storage lane required for the need.",
        ),
        sa.Column(
            "quantity",
            sa.Numeric(precision=12, scale=3),
            nullable=False,
            comment="Requested quantity in the declared unit.",
        ),
        sa.Column(
            "quantity_unit",
            sa.String(length=16),
            nullable=False,
            comment="Controlled quantity unit; no implicit conversion is performed.",
        ),
        sa.Column(
            "priority",
            sa.Integer(),
            nullable=False,
            comment="Priority input from 1 to 5; 5 is highest urgency.",
        ),
        sa.Column(
            "receiving_window_start",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Inclusive receiving-window start.",
        ),
        sa.Column(
            "receiving_window_end",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Exclusive receiving-window end.",
        ),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Inclusive start of this need version.",
        ),
        sa.Column(
            "valid_until",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Exclusive end; NULL means no recorded end.",
        ),
        sa.Column(
            "visibility",
            sa.String(length=16),
            server_default="operational",
            nullable=False,
            comment="Operational or protected need visibility.",
        ),
        sa.Column(
            "updated_by_user_id",
            sa.Uuid(),
            nullable=False,
            comment="Operator responsible for this need version.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this need version was recorded.",
        ),
        sa.CheckConstraint(
            "quantity_unit IN ('kg', 'g', 'unit', 'case', 'box', 'crate', 'litre', 'ml')",
            name="ck_recipient_needs_quantity_unit",
        ),
        sa.CheckConstraint(
            "storage_class IN ('ambient', 'chilled', 'frozen', 'any')",
            name="ck_recipient_needs_storage_class",
        ),
        sa.CheckConstraint(
            "visibility IN ('operational', 'protected')", name="ck_recipient_needs_visibility"
        ),
        sa.CheckConstraint("priority BETWEEN 1 AND 5", name="ck_recipient_needs_priority"),
        sa.CheckConstraint("quantity > 0", name="ck_recipient_needs_quantity_positive"),
        sa.CheckConstraint(
            "receiving_window_end > receiving_window_start",
            name="ck_recipient_needs_receiving_window",
        ),
        sa.CheckConstraint(
            "valid_until IS NULL OR valid_until > valid_from",
            name="ck_recipient_needs_valid_period",
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "site_id",
            "food_category",
            "storage_class",
            "valid_from",
            name="uq_recipient_needs_version",
        ),
    )
    op.create_table(
        "route_input_snapshots",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Internal identity for one immutable route input snapshot.",
        ),
        sa.Column(
            "route_planning_run_id",
            sa.Uuid(),
            nullable=False,
            comment="Planning run that captured this input.",
        ),
        sa.Column(
            "input_kind",
            sa.String(length=16),
            nullable=False,
            comment="Traffic, road, weather, ETA, or operational state input kind.",
        ),
        sa.Column(
            "provider",
            sa.String(length=128),
            nullable=False,
            comment="Provider or source name; exact provider contract is future integration data.",
        ),
        sa.Column(
            "coverage_reference",
            sa.String(length=255),
            nullable=False,
            comment="Road segment, area, route, allocation, or site covered by this snapshot.",
        ),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When the provider/source observed the input.",
        ),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When FoodFlow recorded the input snapshot.",
        ),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Inclusive input validity start.",
        ),
        sa.Column(
            "valid_until",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Exclusive validity end; NULL means provider supplied no explicit end.",
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="Provider response snapshot needed to reconstruct the proposal input.",
        ),
        sa.Column(
            "source_record_id",
            sa.Uuid(),
            nullable=True,
            comment="Optional provenance record for this external input.",
        ),
        sa.CheckConstraint(
            "input_kind IN ('traffic', 'road', 'weather', 'eta', 'allocation', 'condition', 'capacity', 'location')",
            name="ck_route_input_snapshots_kind",
        ),
        sa.CheckConstraint(
            "valid_until IS NULL OR valid_until > valid_from",
            name="ck_route_input_snapshots_valid_period",
        ),
        sa.ForeignKeyConstraint(
            ["route_planning_run_id"], ["route_planning_runs.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["source_record_id"], ["source_records.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "route_proposals",
        sa.Column(
            "id", sa.Uuid(), nullable=False, comment="Internal identity for one proposal version."
        ),
        sa.Column(
            "route_planning_run_id",
            sa.Uuid(),
            nullable=False,
            comment="Planning run that produced this proposal.",
        ),
        sa.Column(
            "version",
            sa.Integer(),
            nullable=False,
            comment="Monotonic proposal version within a planning run.",
        ),
        sa.Column(
            "proposal_status",
            sa.String(length=16),
            server_default="draft",
            nullable=False,
            comment="Draft/superseded/selected; selected still requires a human decision.",
        ),
        sa.Column(
            "proposal_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="Ordered stops and route structure proposed by the agent.",
        ),
        sa.Column(
            "priority_reasons",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="Structured priority reasons; distance cannot be the sole decision.",
        ),
        sa.Column(
            "cost_components",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="Travel, ETA, weather, road, and other explainable cost components.",
        ),
        sa.Column(
            "total_travel_seconds",
            sa.Numeric(precision=12, scale=2),
            nullable=True,
            comment="Estimated total travel duration from the captured inputs.",
        ),
        sa.Column(
            "total_distance_meters",
            sa.Numeric(precision=14, scale=2),
            nullable=True,
            comment="Estimated total distance; a low-priority efficiency factor.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the proposal was generated.",
        ),
        sa.CheckConstraint(
            "proposal_status IN ('draft', 'superseded', 'selected')",
            name="ck_route_proposals_status",
        ),
        sa.CheckConstraint(
            "total_distance_meters IS NULL OR total_distance_meters >= 0",
            name="ck_route_proposals_distance",
        ),
        sa.CheckConstraint(
            "total_travel_seconds IS NULL OR total_travel_seconds >= 0",
            name="ck_route_proposals_travel_seconds",
        ),
        sa.CheckConstraint("version > 0", name="ck_route_proposals_version"),
        sa.ForeignKeyConstraint(
            ["route_planning_run_id"], ["route_planning_runs.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "route_planning_run_id", "version", name="uq_route_proposals_run_version"
        ),
    )
    op.create_table(
        "site_locations",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Internal identifier for this location record and its validity period.",
        ),
        sa.Column(
            "site_id",
            sa.Uuid(),
            nullable=False,
            comment="Site to which this location record belongs.",
        ),
        sa.Column(
            "location_type",
            sa.String(length=32),
            nullable=False,
            comment="Address, research map point, pickup point, or receiving point.",
        ),
        sa.Column(
            "precision_level",
            sa.String(length=24),
            nullable=False,
            comment="Coordinate / address precision used to judge navigation safety.",
        ),
        sa.Column(
            "verification_status",
            sa.String(length=24),
            server_default="unverified",
            nullable=False,
            comment="Whether an operator has confirmed this location for operations.",
        ),
        sa.Column(
            "visibility",
            sa.String(length=16),
            server_default="public",
            nullable=False,
            comment="Public, operational-only, or protected visibility boundary.",
        ),
        sa.Column(
            "address_line1",
            sa.String(length=200),
            nullable=True,
            comment="Street address when available; may be absent for a point-only candidate.",
        ),
        sa.Column(
            "suburb",
            sa.String(length=100),
            nullable=True,
            comment="Suburb or locality from the source location.",
        ),
        sa.Column(
            "city",
            sa.String(length=100),
            nullable=True,
            comment="City or district from the source location.",
        ),
        sa.Column(
            "region",
            sa.String(length=100),
            nullable=True,
            comment="Region from the source location.",
        ),
        sa.Column(
            "postal_code",
            sa.String(length=16),
            nullable=True,
            comment="Postal code when available; stored as text to preserve formatting.",
        ),
        sa.Column(
            "country_code",
            sa.String(length=2),
            server_default="NZ",
            nullable=False,
            comment="ISO-like country code for the location; first slice is NZ-only.",
        ),
        sa.Column(
            "latitude",
            sa.Numeric(precision=9, scale=6),
            nullable=True,
            comment="Latitude in decimal degrees; must be paired with longitude.",
        ),
        sa.Column(
            "longitude",
            sa.Numeric(precision=9, scale=6),
            nullable=True,
            comment="Longitude in decimal degrees; must be paired with latitude.",
        ),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Inclusive start of this location record's validity.",
        ),
        sa.Column(
            "valid_until",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Exclusive end; a correction creates a new record instead of overwriting history.",
        ),
        sa.Column(
            "verified_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the operator confirmation was recorded; required for confirmed points.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this location record was stored.",
        ),
        sa.CheckConstraint(
            "(verification_status = 'unverified' AND verified_at IS NULL) OR (verification_status = 'operator_confirmed' AND verified_at IS NOT NULL)",
            name="ck_site_locations_verification_time",
        ),
        sa.CheckConstraint(
            "location_type IN ('public_address', 'map_point', 'pickup_point', 'receiving_point')",
            name="ck_site_locations_location_type",
        ),
        sa.CheckConstraint(
            "precision_level IN ('exact', 'address_level', 'site_centroid', 'approximate')",
            name="ck_site_locations_precision_level",
        ),
        sa.CheckConstraint(
            "verification_status IN ('unverified', 'operator_confirmed')",
            name="ck_site_locations_verification_status",
        ),
        sa.CheckConstraint(
            "visibility IN ('public', 'operational', 'protected')",
            name="ck_site_locations_visibility",
        ),
        sa.CheckConstraint(
            "(latitude IS NULL AND longitude IS NULL) OR (latitude IS NOT NULL AND longitude IS NOT NULL)",
            name="ck_site_locations_coordinate_pair",
        ),
        sa.CheckConstraint(
            "address_line1 IS NOT NULL OR (latitude IS NOT NULL AND longitude IS NOT NULL)",
            name="ck_site_locations_has_address_or_point",
        ),
        sa.CheckConstraint(
            "latitude IS NULL OR (latitude >= -90 AND latitude <= 90)",
            name="ck_site_locations_latitude_range",
        ),
        sa.CheckConstraint(
            "longitude IS NULL OR (longitude >= -180 AND longitude <= 180)",
            name="ck_site_locations_longitude_range",
        ),
        sa.CheckConstraint(
            "valid_until IS NULL OR valid_until > valid_from", name="ck_site_locations_valid_period"
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "site_id", name="uq_site_locations_id_site"),
    )
    op.create_table(
        "donation_items",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Internal identity for this donation line; not a GTIN.",
        ),
        sa.Column(
            "donation_id", sa.Uuid(), nullable=False, comment="Donation batch containing this line."
        ),
        sa.Column(
            "line_number",
            sa.Integer(),
            nullable=False,
            comment="Stable line number within this donation submission.",
        ),
        sa.Column(
            "food_product_id",
            sa.Uuid(),
            nullable=True,
            comment="Optional reusable product identity; no-barcode lines leave this NULL.",
        ),
        sa.Column(
            "product_name_snapshot",
            sa.String(length=200),
            nullable=False,
            comment="Product name at listing time; not overwritten by product master changes.",
        ),
        sa.Column(
            "brand_snapshot",
            sa.String(length=200),
            nullable=True,
            comment="Brand at listing time, if known.",
        ),
        sa.Column(
            "variant_snapshot",
            sa.String(length=200),
            nullable=True,
            comment="Size/flavour/variant at listing time, if known.",
        ),
        sa.Column(
            "gtin_snapshot",
            sa.String(length=14),
            nullable=True,
            comment="Optional GTIN copied into the historical item snapshot.",
        ),
        sa.Column(
            "lot_code",
            sa.String(length=100),
            nullable=True,
            comment="Lot or batch mark for this physical food line, if known.",
        ),
        sa.Column(
            "quantity",
            sa.Numeric(precision=12, scale=3),
            nullable=False,
            comment="Quantity offered in the declared unit; initial item is not split in this slice.",
        ),
        sa.Column(
            "quantity_unit",
            sa.String(length=16),
            nullable=False,
            comment="Controlled quantity unit; conversions are not implied by the schema.",
        ),
        sa.Column(
            "storage_class",
            sa.String(length=16),
            nullable=False,
            comment="Required storage lane: ambient, chilled, frozen, or unknown.",
        ),
        sa.Column(
            "date_mark_type",
            sa.String(length=16),
            nullable=False,
            comment="Date meaning is separate from the date value.",
        ),
        sa.Column(
            "date_mark",
            sa.Date(),
            nullable=True,
            comment="Use-by, best-before, packed-on, or NULL when not applicable/known.",
        ),
        sa.Column(
            "packaging_condition",
            sa.String(length=16),
            server_default="unknown",
            nullable=False,
            comment="Listing-time packaging state; unsafe states are handled by future rules.",
        ),
        sa.Column(
            "recall_status",
            sa.String(length=16),
            server_default="not_checked",
            nullable=False,
            comment="Recall fact used by a future non-overridable eligibility rule.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this donation line was created.",
        ),
        sa.CheckConstraint(
            "date_mark_type IN ('none', 'unknown') OR date_mark IS NOT NULL",
            name="ck_donation_items_date_mark_value",
        ),
        sa.CheckConstraint(
            "date_mark_type IN ('use_by', 'best_before', 'packed_on', 'none', 'unknown')",
            name="ck_donation_items_date_mark_type",
        ),
        sa.CheckConstraint(
            "packaging_condition IN ('sealed', 'opened', 'damaged', 'unknown')",
            name="ck_donation_items_packaging_condition",
        ),
        sa.CheckConstraint(
            "quantity_unit IN ('kg', 'g', 'unit', 'case', 'box', 'crate', 'litre', 'ml')",
            name="ck_donation_items_quantity_unit",
        ),
        sa.CheckConstraint(
            "recall_status IN ('not_checked', 'not_recalled', 'recalled')",
            name="ck_donation_items_recall_status",
        ),
        sa.CheckConstraint(
            "storage_class IN ('ambient', 'chilled', 'frozen', 'unknown')",
            name="ck_donation_items_storage_class",
        ),
        sa.CheckConstraint("line_number > 0", name="ck_donation_items_line_number"),
        sa.CheckConstraint("quantity > 0", name="ck_donation_items_quantity_positive"),
        sa.ForeignKeyConstraint(["donation_id"], ["donations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["food_product_id"], ["food_products.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("donation_id", "line_number", name="uq_donation_items_line_number"),
    )
    op.create_table(
        "donation_status_events",
        sa.Column("id", sa.Uuid(), nullable=False, comment="Internal append-only event identity."),
        sa.Column(
            "donation_id",
            sa.Uuid(),
            nullable=False,
            comment="Donation aggregate whose state history is recorded.",
        ),
        sa.Column(
            "event_type",
            sa.String(length=24),
            nullable=False,
            comment="Success-path transition or review event.",
        ),
        sa.Column(
            "actor_type",
            sa.String(length=8),
            server_default="user",
            nullable=False,
            comment="Whether the event was recorded by a user or deterministic system rule.",
        ),
        sa.Column(
            "actor_user_id",
            sa.Uuid(),
            nullable=True,
            comment="User actor when actor_type is user; NULL for system events.",
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When the business event occurred.",
        ),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the event was recorded.",
        ),
        sa.Column(
            "notes",
            sa.String(length=500),
            nullable=True,
            comment="Optional event context; failure-specific reason fields are deferred.",
        ),
        sa.CheckConstraint(
            "(actor_type = 'user' AND actor_user_id IS NOT NULL) OR (actor_type = 'system' AND actor_user_id IS NULL)",
            name="ck_donation_status_events_actor_reference",
        ),
        sa.CheckConstraint(
            "actor_type IN ('user', 'system')", name="ck_donation_status_events_actor_type"
        ),
        sa.CheckConstraint(
            "event_type IN ('created', 'listed', 'manual_review', 'hard_blocked', 'collected', 'delivered')",
            name="ck_donation_status_events_type",
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["donation_id"], ["donations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "route_decisions",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Internal identity for one route decision fact.",
        ),
        sa.Column(
            "route_proposal_id",
            sa.Uuid(),
            nullable=False,
            comment="Proposal on which the human decision was made.",
        ),
        sa.Column(
            "decision_type",
            sa.String(length=32),
            nullable=False,
            comment="Driver confirmation or coordinator exception decision.",
        ),
        sa.Column(
            "decision",
            sa.String(length=16),
            nullable=False,
            comment="Approved or rejected; no agent decision commits a route.",
        ),
        sa.Column(
            "actor_user_id",
            sa.Uuid(),
            nullable=False,
            comment="Human actor responsible for committing or rejecting the proposal.",
        ),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the route decision was made.",
        ),
        sa.Column(
            "comment", sa.String(length=500), nullable=True, comment="Optional human explanation."
        ),
        sa.CheckConstraint("decision IN ('approved', 'rejected')", name="ck_route_decisions_value"),
        sa.CheckConstraint(
            "decision_type IN ('driver_confirmation', 'coordinator_exception')",
            name="ck_route_decisions_type",
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["route_proposal_id"], ["route_proposals.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "route_proposal_id", "decision_type", name="uq_route_decisions_proposal_type"
        ),
    )
    op.create_table(
        "deliveries",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Internal identity for one committed delivery job.",
        ),
        sa.Column(
            "route_decision_id",
            sa.Uuid(),
            nullable=False,
            comment="Approved route decision that committed this delivery.",
        ),
        sa.Column(
            "driver_user_id",
            sa.Uuid(),
            nullable=False,
            comment="Driver executing the approved delivery.",
        ),
        sa.Column(
            "planned_departure_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Departure time from the committed route plan.",
        ),
        sa.Column(
            "committed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the approved route became a delivery job.",
        ),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default="assigned",
            nullable=False,
            comment="Success-path execution state; failed/cancelled states are deferred.",
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the driver started the delivery.",
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When successful delivery completion was recorded.",
        ),
        sa.CheckConstraint(
            "(status = 'assigned' AND started_at IS NULL AND completed_at IS NULL) OR (status = 'started' AND started_at IS NOT NULL AND completed_at IS NULL) OR (status = 'completed' AND started_at IS NOT NULL AND completed_at IS NOT NULL)",
            name="ck_deliveries_status_timestamps",
        ),
        sa.CheckConstraint(
            "status IN ('assigned', 'started', 'completed')", name="ck_deliveries_status"
        ),
        sa.ForeignKeyConstraint(["driver_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["route_decision_id"], ["route_decisions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("route_decision_id", name="uq_deliveries_route_decision"),
    )
    op.create_table(
        "food_condition_observations",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Internal identity for one observed condition fact.",
        ),
        sa.Column(
            "donation_item_id",
            sa.Uuid(),
            nullable=False,
            comment="Food line whose condition was observed.",
        ),
        sa.Column(
            "observed_by_user_id",
            sa.Uuid(),
            nullable=False,
            comment="Actor responsible for recording this observation.",
        ),
        sa.Column(
            "checkpoint",
            sa.String(length=16),
            nullable=False,
            comment="Operational checkpoint: listing, pickup, or delivery.",
        ),
        sa.Column(
            "condition_status",
            sa.String(length=16),
            nullable=False,
            comment="Observation outcome used by future safety evaluation.",
        ),
        sa.Column(
            "temperature_celsius",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
            comment="Observed temperature when relevant; NULL means not measured.",
        ),
        sa.Column(
            "notes",
            sa.String(length=500),
            nullable=True,
            comment="Short operational observation; not a replacement for controlled status.",
        ),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When the condition was observed.",
        ),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When FoodFlow recorded the observation.",
        ),
        sa.CheckConstraint(
            "checkpoint IN ('listing', 'pickup', 'delivery')",
            name="ck_food_condition_observations_checkpoint",
        ),
        sa.CheckConstraint(
            "condition_status IN ('acceptable', 'manual_review', 'unsafe', 'unknown')",
            name="ck_food_condition_observations_condition_status",
        ),
        sa.CheckConstraint(
            "temperature_celsius IS NULL OR temperature_celsius BETWEEN -100 AND 100",
            name="ck_food_condition_observations_temperature_range",
        ),
        sa.ForeignKeyConstraint(["donation_item_id"], ["donation_items.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["observed_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "match_runs",
        sa.Column(
            "id", sa.Uuid(), nullable=False, comment="Internal identity for one matching execution."
        ),
        sa.Column(
            "donation_item_id",
            sa.Uuid(),
            nullable=False,
            comment="Donation item being matched in this run.",
        ),
        sa.Column(
            "requested_by_user_id",
            sa.Uuid(),
            nullable=True,
            comment="Optional human initiator; system-triggered runs may have NULL.",
        ),
        sa.Column(
            "policy_version",
            sa.String(length=64),
            nullable=False,
            comment="Deterministic feasibility and priority policy version.",
        ),
        sa.Column(
            "model_identifier",
            sa.String(length=128),
            nullable=True,
            comment="Optional agent/model identifier used only for candidate ranking.",
        ),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default="started",
            nullable=False,
            comment="Run state; no candidate is an allocation by itself.",
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the matching run began.",
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the matching run reached a result state.",
        ),
        sa.CheckConstraint(
            "status IN ('started', 'completed', 'no_feasible_candidates', 'manual_review')",
            name="ck_match_runs_status",
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR completed_at >= started_at",
            name="ck_match_runs_completion_time",
        ),
        sa.ForeignKeyConstraint(["donation_item_id"], ["donation_items.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["requested_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "delivery_stops",
        sa.Column(
            "id", sa.Uuid(), nullable=False, comment="Internal identity for one delivery stop."
        ),
        sa.Column(
            "delivery_id",
            sa.Uuid(),
            nullable=False,
            comment="Committed delivery containing this stop.",
        ),
        sa.Column(
            "stop_sequence",
            sa.Integer(),
            nullable=False,
            comment="Approved route order; never overwritten by actual order.",
        ),
        sa.Column(
            "actual_sequence",
            sa.Integer(),
            nullable=True,
            comment="Observed order when it differs from the approved plan.",
        ),
        sa.Column(
            "stop_type",
            sa.String(length=16),
            nullable=False,
            comment="Pickup, delivery, or approved cross-dock stop.",
        ),
        sa.Column("site_id", sa.Uuid(), nullable=False, comment="Operational site for this stop."),
        sa.Column(
            "site_location_id",
            sa.Uuid(),
            nullable=False,
            comment="Exact approved operational location used by navigation.",
        ),
        sa.Column(
            "window_start",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Optional stop receiving/collection window start.",
        ),
        sa.Column(
            "window_end",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Optional stop receiving/collection window end.",
        ),
        sa.Column(
            "planned_arrival_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Planned arrival time from the committed route.",
        ),
        sa.Column(
            "planned_departure_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Planned departure time from the committed route.",
        ),
        sa.Column(
            "actual_arrival_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Actual arrival time recorded by the driver.",
        ),
        sa.Column(
            "actual_departure_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Actual departure time recorded by the driver.",
        ),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default="planned",
            nullable=False,
            comment="Success-path stop state; failed stop behavior is deferred.",
        ),
        sa.Column(
            "result_note",
            sa.String(length=500),
            nullable=True,
            comment="Short successful-stop note; failure reasons are deferred.",
        ),
        sa.CheckConstraint(
            "status IN ('planned', 'in_progress', 'completed')", name="ck_delivery_stops_status"
        ),
        sa.CheckConstraint(
            "stop_type IN ('pickup', 'delivery', 'cross_dock')", name="ck_delivery_stops_type"
        ),
        sa.CheckConstraint(
            "actual_departure_at IS NULL OR actual_arrival_at IS NOT NULL AND actual_departure_at >= actual_arrival_at",
            name="ck_delivery_stops_actual_times",
        ),
        sa.CheckConstraint(
            "actual_sequence IS NULL OR actual_sequence > 0",
            name="ck_delivery_stops_actual_sequence",
        ),
        sa.CheckConstraint("stop_sequence > 0", name="ck_delivery_stops_sequence"),
        sa.CheckConstraint(
            "window_end IS NULL OR window_start IS NOT NULL AND window_end > window_start",
            name="ck_delivery_stops_window",
        ),
        sa.ForeignKeyConstraint(["delivery_id"], ["deliveries.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["site_location_id", "site_id"],
            ["site_locations.id", "site_locations.site_id"],
            name="fk_delivery_stops_location_site",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("delivery_id", "id", name="uq_delivery_stops_delivery_id"),
        sa.UniqueConstraint("delivery_id", "stop_sequence", name="uq_delivery_stops_sequence"),
    )
    op.create_table(
        "match_candidates",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Internal identity for one recipient candidate result.",
        ),
        sa.Column(
            "match_run_id",
            sa.Uuid(),
            nullable=False,
            comment="Matching run that evaluated this candidate.",
        ),
        sa.Column(
            "recipient_site_id",
            sa.Uuid(),
            nullable=False,
            comment="Recipient site evaluated for the donation item.",
        ),
        sa.Column(
            "feasibility_status",
            sa.String(length=16),
            nullable=False,
            comment="Deterministic result before agent ranking.",
        ),
        sa.Column(
            "reason_code",
            sa.String(length=64),
            nullable=False,
            comment="Stable explanation code for feasible or excluded result.",
        ),
        sa.Column(
            "reason_components",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="Structured safety, capacity, need, ETA, and distance evidence.",
        ),
        sa.Column(
            "agent_rank",
            sa.Integer(),
            nullable=True,
            comment="Agent rank among feasible candidates; NULL for excluded candidates.",
        ),
        sa.Column(
            "priority_score",
            sa.Numeric(precision=12, scale=6),
            nullable=True,
            comment="Optional reproducible ranking score; not a hidden authority decision.",
        ),
        sa.Column(
            "evaluated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the candidate facts were evaluated.",
        ),
        sa.CheckConstraint(
            "feasibility_status IN ('feasible', 'infeasible', 'manual_review')",
            name="ck_match_candidates_feasibility_status",
        ),
        sa.CheckConstraint(
            "agent_rank IS NULL OR agent_rank > 0", name="ck_match_candidates_agent_rank"
        ),
        sa.ForeignKeyConstraint(["match_run_id"], ["match_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["recipient_site_id"], ["sites.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "recipient_site_id", name="uq_match_candidates_id_site"),
        sa.UniqueConstraint(
            "match_run_id", "recipient_site_id", name="uq_match_candidates_run_site"
        ),
    )
    op.create_table(
        "allocations",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Internal identity for one recipient allocation history.",
        ),
        sa.Column(
            "donation_item_id",
            sa.Uuid(),
            nullable=False,
            comment="Donation item reserved for one recipient in this success slice.",
        ),
        sa.Column(
            "recipient_site_id",
            sa.Uuid(),
            nullable=False,
            comment="One recipient site for the initial non-split allocation.",
        ),
        sa.Column(
            "match_candidate_id",
            sa.Uuid(),
            nullable=False,
            comment="Candidate confirmed before this allocation was reserved.",
        ),
        sa.Column(
            "allocated_quantity",
            sa.Numeric(precision=12, scale=3),
            nullable=False,
            comment="Allocated quantity in the declared unit; initial item is not split.",
        ),
        sa.Column(
            "quantity_unit",
            sa.String(length=16),
            nullable=False,
            comment="Unit of allocated_quantity.",
        ),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default="reserved",
            nullable=False,
            comment="Success-path allocation state; release/failure states are deferred.",
        ),
        sa.Column(
            "reserved_by_user_id",
            sa.Uuid(),
            nullable=False,
            comment="Driver or authorised actor who created the reservation.",
        ),
        sa.Column(
            "reserved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the reservation was created.",
        ),
        sa.Column(
            "confirmed_by_user_id",
            sa.Uuid(),
            nullable=True,
            comment="Recipient responder who accepted the reservation.",
        ),
        sa.Column(
            "confirmed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When recipient acceptance changed the reservation to confirmed.",
        ),
        sa.Column(
            "fulfilled_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the successful delivery fulfilment was recorded.",
        ),
        sa.CheckConstraint(
            "(status = 'reserved' AND confirmed_at IS NULL AND fulfilled_at IS NULL) OR (status = 'confirmed' AND confirmed_at IS NOT NULL AND fulfilled_at IS NULL) OR (status = 'fulfilled' AND confirmed_at IS NOT NULL AND fulfilled_at IS NOT NULL)",
            name="ck_allocations_status_timestamps",
        ),
        sa.CheckConstraint(
            "quantity_unit IN ('kg', 'g', 'unit', 'case', 'box', 'crate', 'litre', 'ml')",
            name="ck_allocations_quantity_unit",
        ),
        sa.CheckConstraint(
            "status IN ('reserved', 'confirmed', 'fulfilled')", name="ck_allocations_status"
        ),
        sa.CheckConstraint("allocated_quantity > 0", name="ck_allocations_quantity_positive"),
        sa.ForeignKeyConstraint(["confirmed_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["donation_item_id"], ["donation_items.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["match_candidate_id", "recipient_site_id"],
            ["match_candidates.id", "match_candidates.recipient_site_id"],
            name="fk_allocations_candidate_recipient_site",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["recipient_site_id"], ["sites.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["reserved_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_allocations_active_item",
        "allocations",
        ["donation_item_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('reserved', 'confirmed')"),
    )
    op.create_table(
        "delivery_status_events",
        sa.Column(
            "id", sa.Uuid(), nullable=False, comment="Internal append-only delivery event identity."
        ),
        sa.Column(
            "delivery_id",
            sa.Uuid(),
            nullable=False,
            comment="Delivery aggregate whose event is recorded.",
        ),
        sa.Column(
            "stop_id",
            sa.Uuid(),
            nullable=True,
            comment="Optional stop-specific event; NULL means delivery-level event.",
        ),
        sa.Column(
            "event_type",
            sa.String(length=16),
            nullable=False,
            comment="Success-path delivery or stop event type.",
        ),
        sa.Column(
            "actor_type",
            sa.String(length=8),
            server_default="user",
            nullable=False,
            comment="Whether the event was recorded by a user or system rule.",
        ),
        sa.Column(
            "actor_user_id",
            sa.Uuid(),
            nullable=True,
            comment="User actor when actor_type is user; NULL for system events.",
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When the delivery event occurred.",
        ),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the event was recorded.",
        ),
        sa.Column(
            "notes",
            sa.String(length=500),
            nullable=True,
            comment="Optional successful-stop context; failure-specific reasons are deferred.",
        ),
        sa.CheckConstraint(
            "(actor_type = 'user' AND actor_user_id IS NOT NULL) OR (actor_type = 'system' AND actor_user_id IS NULL)",
            name="ck_delivery_status_events_actor_reference",
        ),
        sa.CheckConstraint(
            "actor_type IN ('user', 'system')", name="ck_delivery_status_events_actor_type"
        ),
        sa.CheckConstraint(
            "event_type IN ('assigned', 'started', 'arrived', 'collected', 'delivered', 'completed')",
            name="ck_delivery_status_events_type",
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["delivery_id", "stop_id"],
            ["delivery_stops.delivery_id", "delivery_stops.id"],
            name="fk_delivery_status_events_delivery_stop",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["delivery_id"], ["deliveries.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "match_decisions",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Internal identity for one human decision fact.",
        ),
        sa.Column(
            "match_candidate_id",
            sa.Uuid(),
            nullable=False,
            comment="Candidate on which the actor made this decision.",
        ),
        sa.Column(
            "decision_type",
            sa.String(length=32),
            nullable=False,
            comment="Separates driver confirmation, coordinator exception, and recipient response.",
        ),
        sa.Column(
            "decision",
            sa.String(length=16),
            nullable=False,
            comment="Decision value constrained by decision_type.",
        ),
        sa.Column(
            "actor_user_id",
            sa.Uuid(),
            nullable=False,
            comment="Actor responsible for the decision; role is checked by future service logic.",
        ),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the business decision was made.",
        ),
        sa.Column(
            "comment",
            sa.String(length=500),
            nullable=True,
            comment="Optional human explanation; hard safety blocks cannot be overridden here.",
        ),
        sa.CheckConstraint(
            "(decision_type = 'driver_confirmation' AND decision IN ('confirmed', 'rejected')) OR (decision_type = 'coordinator_exception' AND decision IN ('approved', 'rejected')) OR (decision_type = 'recipient_acceptance' AND decision IN ('accepted', 'declined'))",
            name="ck_match_decisions_value",
        ),
        sa.CheckConstraint(
            "decision_type IN ('driver_confirmation', 'coordinator_exception', 'recipient_acceptance')",
            name="ck_match_decisions_type",
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["match_candidate_id"], ["match_candidates.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "match_candidate_id", "decision_type", name="uq_match_decisions_candidate_type"
        ),
    )
    op.create_table(
        "allocation_status_events",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Internal append-only allocation event identity.",
        ),
        sa.Column(
            "allocation_id",
            sa.Uuid(),
            nullable=False,
            comment="Allocation whose state history is recorded.",
        ),
        sa.Column(
            "event_type",
            sa.String(length=16),
            nullable=False,
            comment="Reserved, confirmed, or fulfilled success-path event.",
        ),
        sa.Column(
            "actor_type",
            sa.String(length=8),
            server_default="user",
            nullable=False,
            comment="Whether the event was recorded by a user or system rule.",
        ),
        sa.Column(
            "actor_user_id",
            sa.Uuid(),
            nullable=True,
            comment="User actor when actor_type is user; NULL for system events.",
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When the allocation event occurred.",
        ),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the event was recorded.",
        ),
        sa.Column(
            "notes",
            sa.String(length=500),
            nullable=True,
            comment="Optional success-path context; failure-specific reasons are deferred.",
        ),
        sa.CheckConstraint(
            "(actor_type = 'user' AND actor_user_id IS NOT NULL) OR (actor_type = 'system' AND actor_user_id IS NULL)",
            name="ck_allocation_status_events_actor_reference",
        ),
        sa.CheckConstraint(
            "actor_type IN ('user', 'system')", name="ck_allocation_status_events_actor_type"
        ),
        sa.CheckConstraint(
            "event_type IN ('reserved', 'confirmed', 'fulfilled')",
            name="ck_allocation_status_events_type",
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["allocation_id"], ["allocations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "delivery_allocations",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Internal identity for one delivery/allocation junction row.",
        ),
        sa.Column(
            "delivery_id",
            sa.Uuid(),
            nullable=False,
            comment="Committed delivery carrying the allocation.",
        ),
        sa.Column(
            "allocation_id",
            sa.Uuid(),
            nullable=False,
            comment="Confirmed allocation included in this delivery.",
        ),
        sa.Column(
            "pickup_stop_id", sa.Uuid(), nullable=False, comment="Pickup stop for this allocation."
        ),
        sa.Column(
            "delivery_stop_id",
            sa.Uuid(),
            nullable=False,
            comment="Delivery stop for this allocation.",
        ),
        sa.ForeignKeyConstraint(["allocation_id"], ["allocations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["delivery_id", "delivery_stop_id"],
            ["delivery_stops.delivery_id", "delivery_stops.id"],
            name="fk_delivery_allocations_delivery_stop",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["delivery_id", "pickup_stop_id"],
            ["delivery_stops.delivery_id", "delivery_stops.id"],
            name="fk_delivery_allocations_pickup_stop",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["delivery_id"], ["deliveries.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "delivery_id", "allocation_id", name="uq_delivery_allocations_delivery_allocation"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("delivery_allocations")
    op.drop_table("allocation_status_events")
    op.drop_table("match_decisions")
    op.drop_table("delivery_status_events")
    op.drop_index(
        "uq_allocations_active_item",
        table_name="allocations",
        postgresql_where=sa.text("status IN ('reserved', 'confirmed')"),
    )
    op.drop_table("allocations")
    op.drop_table("match_candidates")
    op.drop_table("delivery_stops")
    op.drop_table("match_runs")
    op.drop_table("food_condition_observations")
    op.drop_table("deliveries")
    op.drop_table("route_decisions")
    op.drop_table("donation_status_events")
    op.drop_table("donation_items")
    op.drop_table("site_locations")
    op.drop_table("route_proposals")
    op.drop_table("route_input_snapshots")
    op.drop_table("recipient_needs")
    op.drop_table("recipient_capabilities")
    op.drop_table("recipient_availability_snapshots")
    op.drop_table("organisation_memberships")
    op.drop_table("food_products")
    op.drop_table("donations")
    op.drop_table("source_records")
    op.drop_table("sites")
    op.drop_table("route_planning_runs")
    op.drop_table("organisation_roles")
    op.drop_index("uq_users_email_ci", table_name="users")
    op.drop_table("users")
    op.drop_table("organisations")
    op.drop_table("import_batches")
    # ### end Alembic commands ###
